# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
resins = Resin.create!([
                            { product_code:	'ABS'				},
                            { product_code:	'ABS HH'				},
                            { product_code:	'ABS PLATING'				},
                            { product_code:	'ABS FR'				},
                            { product_code:	'ASA'				},
                            { product_code:	'PC'				},
                            { product_code:	'PC FR'				},
                            { product_code:	'PC GF10'				},
                            { product_code:	'PC GF20'				},
                            { product_code:	'PC GF30'				},
                            { product_code:	'PC GF40'				},
                            { product_code:	'PC/ABS'				},
                            { product_code:	'PC/ABS PLATING'				},
                            { product_code:	'PC/ASA'				},
                            { product_code:	'PC/PBT'				},
                            { product_code:	'PA6'				},
                            { product_code:	'PA6 Graphite Filled/Anti-Stat'			},
	                          { product_code:	'PA6 GF10'				},
	{ product_code:	'PA6 GF13'				},
	{ product_code:	'PA6 GF20'				},
	{ product_code:	'PA6 GF30'				},
	{ product_code:	'PA6 GF33'				},
	{ product_code:	'PA66'				},
	{ product_code:	'PA66 GF10'				},
	{ product_code:	'PA66 GF13'				},
	{ product_code:	'PA66 GF20'				},
	{ product_code:	'PA66 GF30'				},
	{ product_code:	'PA66 GF33'				},
	{ product_code:	'PA612'				},
	{ product_code:	'PA MXD6'				},
	{ product_code:	'PBT'				},
	{ product_code:	'PBT GF10'				},
	{ product_code:	'PBT GF15'				},
	{ product_code:	'PBT GF30'				},
	{ product_code:	'PBT GF40'				},
	{ product_code:	'PBT FR'				},
	{ product_code:	'PEI'				},
	{ product_code:	'PET'				},
	{ product_code:	'PETG'				},
	{ product_code:	'COPET'				},
	{ product_code:	'COC'				},
	{ product_code:	'LCP'				},
	{ product_code:	'PPS'				},
	{ product_code:	'PPE/PS'				},
	{ product_code:	'PPE/PA'			},
                            { product_code:	'PP Clarified'				},
                            { product_code:	'PPH'				},
                            { product_code:	'PPC'				},
                            { product_code:	'PMMA'				},
                            { product_code:	'HDPE'				},
                            { product_code:	'LDPE'				},
                            { product_code:	'PE'				},
                            { product_code:	'PS'				},
                            { product_code:	'CPS'				},
                            { product_code:	'HIPS'				},
                            { product_code:	'TPX'				}
                        ])
